pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/nxshh/DevOps_Internship.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                sh 'npm test || true'
            }
        }

        stage('Docker Build & Push') {
            steps {
                sh '''
                docker build -t nxshh/nodejs-demo-app .
                docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                docker push nxshh/nodejs-demo-app
                '''
            }
        }
    }
}
