pipeline {
    agent {
        docker {
            image 'node:18'
        }
    }

    stages {

        stage('Build') {
            steps {
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                sh 'npm test'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker build -t nodejs-jenkins-app .'
            }
        }
    }
}
